data = [
    {
        'no':1,
        'name':"cristiano Ronaldo",
        'followers': 466,
        'country': 'Portuguese',
        'description': "a football player,",
    },
    {
        'no':2,
        'name': "Lionel Messi",
        'followers' : 348,
        'country': 'Spanish',
        'description': "a Footballer",
    },
    {
        'no':3,
        'name': "Sachin Tendulkar",
        'followers' : 35,
        'country': 'India',
        'description': "a former Indian international cricketer",
    },
    {
        'no':4,
        'name': "Virat Kohli",
        'followers' : 207,
        'country': 'India',
        'description': "an Indian International cricketer",
    },
    {
        'no':5,
        'name': "M.S.Dhoni",
        'followers' : 39,
        'country': 'India',
        'description': "an Indian cricketer",
    },
    {
        'no':6,
        'name': "Shraddha Kapoor",
        'followers' : 74,
        'country': 'India',
        'description': "an Indian actress",
    },
    {
        'no':7,
        'name': "Salman Khan",
        'followers' : 53,
        'country': 'India',
        'description': "an Indian actor, film producer",
    },
    {
        'no':8,
        'name': "Shahrukh Khan",
        'followers' : 30,
        'country': 'India',
        'description': "an Indian actor, film producer,",
    },
    {
        'no':9,
        'name': "Donald J. Trump",
        'followers' : 23.5,
        'country': 'United States',
        'description': " an American politician and businessman",
    },
    {
        'no':10,
        'name': "Narendra Modi",
        'followers' : 69,
        'country': 'Indian',
        'description': "an Indian politician",
    },
    {
        'no':11,
        'name': "AB de Villiers",
        'followers' : 18.5,
        'country': 'South Africa',
        'description': "a former South African international cricketer",
    },
    {
        'no':12,
        'name': "Arijit Singh",
        'followers' : 6,
        'country': 'Indian',
        'description': "an Indian singer ",
    },
    {
        'no':13,
        'name': "Ratan Tata",
        'followers' : 6.5,
        'country': 'Indian',
        'description': " an Indian industrialist, philanthropist ",
    },
    {
        'no':14,
        'name': "Space X",
        'followers' : 15,
        'country': 'America',
        'description': "an American spacekraft company",
    },
    {
        'no':15,
        'name': "Nasa",
        'followers' : 79,
        'country': 'Space Agency',
        'description': "United States",
    },
    {
        'no':16,
        'name': "jeffbezos",
        'followers' : 4,
        'country': 'United States',
        'description': "an American entrepreneur, media proprietor, investor, computer engineer, and commercial astronaut",
    },
    {
        'no':17,
        'name': "sundarpichai",
        'followers' : 1.5,
        'country': 'America/India',
        'description': "an Indian-American business executive",
    },
    {
        'no':18,
        'name': "deepikapadukone",
        'followers' : 68,
        'country': 'India',
        'description': "an Indian actress",
    },
    {
        'no':19,
        'name': "Amazon india",
        'followers' : 2,
        'country': 'India',
        'description': "Indian/American E-commerce company",
    },
    {
        'no':20,
        'name': "Flipkart",
        'followers' : 3,
        'country': 'India',
        'description': "Indian E-commerce company",
    },
    {
        'no':21,
        'name': "The Rock",
        'followers' : 327,
        'country': 'Canada/America',
        'description': "an American actor, businessman, and former professional wrestler",
    },
    {
        'no':22,
        'name': "Ariana Grande",
        'followers' : 321,
        'country': 'America',
        'description': "an American actress and singer",
    },
]

